---
# Source: /devops/azure/chart/templates/virtual-service.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Chart.Name }}
  namespace: osdu
spec:
  hosts:
  - "{{ .Values.istioDnsHost }}"
  gateways:
  - istio-gateway
  http:  
  - match:
    - uri:
        prefix: "/api/{{ .Chart.Name }}/v2"
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: 80
    corsPolicy:
      maxAge: "60m"
      allowCredentials: true
      allowHeaders:
      - Authorization
      - Data-Partition-Id
      - Correlation-Id
      allowMethods:
      - POST
      - GET
      - PUT
      - PATCH
      - DELETE
      allowOrigins:
      - prefix: "*" 